export const INJECT_DEFECTS = 'INJECT_DEFECTS';
export const UPDATE_DEFECTS_BY_DATE = 'UPDATE_DEFECTS_BY_DATE';
export const ADD_SINGLE_DEFECT = 'ADD_SINGLE_DEFECT';
// dates
export const SET_DATE_RANGE = 'SET_DATE_RANGE';
